version: '3'
services:
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - '5552:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/minio:/data
    command: server /data

volumes:
  postgres:
